server:
  port: 7777
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://106.53.27.170:3307/bootscala
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
